### ISSUE TITLE
Re: Pretrained inverted latent codes/weights for a new dataset

### ISSUE THREAD

**Issue by Parul-Gupta** [chansey0529/LSO#4]
Hi authors,
Kudos for this great work!
I was wondering how one can get the pretrained latent codes and feature extractor weights on a new dataset (other than Flowers/VGGFace/AnimalFaces) using this codebase (in the getting started section). Could you please give a direction to follow?

Thanks

**Comment by chansey0529** [comment]
Thanks for your attention. In order to get the inverted latent codes, there are two ways. One is to train an encoder([psp](https://github.com/eladrich/pixel2style2pixel), [e4e](https://github.com/omertov/encoder4editing)) using the seen images, and you can encode the unseen images with the encoder. However, we find that the encoder can not handle significant domain gaps between seen and unseen categories, thus we recommend another line of inversion, which is a direct optimization of the latent code. These lines of research involve i2s, i2s++, and [ii2s](https://github.com/ZPdesu/II2S). To enable the code for inversion, you might need to substitute the [stylegan2 implemented by rosinality](https://github.com/rosinality/stylegan2-pytorch) with the [official stylegan](https://github.com/NVlabs/stylegan2-ada-pytorch) in their code. The optimization-based method can lessen the influence of the category gap of unseen data to some extent.
